"""Immutable synthetic Codex destination and expected-admission cases."""

CODEX_DESTINATIONS = (
    (
        "O0",
        "https://chatgpt.com/backend-api/codex",
        "codex_oauth",
        "https://chatgpt.com/backend-api/codex",
    ),
    (
        "O1",
        "https://CHATGPT.COM:443/backend-api/codex/",
        "codex_oauth",
        "https://CHATGPT.COM:443/backend-api/codex",
    ),
    (
        "O2",
        "https://chatgpt.com/backend-api/codex///",
        "codex_oauth",
        "https://chatgpt.com/backend-api/codex",
    ),
    ("C0", "https://proxy.invalid/codex", "codex_compat", "https://proxy.invalid/codex"),
    ("C1", "http://127.0.0.1:8080/codex", "codex_compat", "http://127.0.0.1:8080/codex"),
    ("C2", "http://gpu.invalid:8080/codex", "codex_compat", "http://gpu.invalid:8080/codex"),
    ("C3", "http://[::1]:8080/codex", "codex_compat", "http://[::1]:8080/codex"),
    (
        "C4",
        "https://proxy.invalid:8443/custom/path",
        "codex_compat",
        "https://proxy.invalid:8443/custom/path",
    ),
    ("C5", "https://api.chatgpt.com/codex", "codex_compat", "https://api.chatgpt.com/codex"),
    ("X0", "http://chatgpt.com/backend-api/codex", None, None),
    ("X1", "https://chatgpt.com:8443/backend-api/codex", None, None),
    ("X2", "https://chatgpt.com/not-codex", None, None),
    ("X3", "https://user:pass@proxy.invalid/codex", None, None),
    ("X4", "https://proxy.invalid/codex?mode=test", None, None),
    ("X5", "https://proxy.invalid/codex#fragment", None, None),
    ("X6", "https://proxy.invalid:65536/codex", None, None),
    ("X7", "https://proxy.invalid:/codex", None, None),
    ("X8", "https://proxy.invalid/codex\\path", None, None),
    ("X9", "http://[::1/codex", None, None),
    ("X10", "https:///codex", None, None),
    ("X11", "ftp://proxy.invalid/codex", None, None),
    ("X12", "\thttps://proxy.invalid/codex", None, None),
    ("X13", "https://@proxy.invalid/codex", None, None),
    ("X14", "https://proxy.invalid:invalid/codex", None, None),
    ("X15", "https://pro\nxy.invalid/codex", None, None),
    ("X16", "\u0000https://proxy.invalid/codex", None, None),
    ("X17", "https://proxy.invalid/codex", None, None),
    ("X18", "/", None, None),
    ("X19", "///", None, None),
)
